# SQL COMMAND TO REBUILD DB
version: '3'

services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    volumes:
      - ./sql-scripts:/var/opt/mssql/scripts
      - ~/GitHub/Data/mssql:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
