/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserInput
 */
export interface CreateUserInput {
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserInput
     */
    password: string;
}

/**
 * Check if a given object implements the CreateUserInput interface.
 */
export function instanceOfCreateUserInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function CreateUserInputFromJSON(json: any): CreateUserInput {
    return CreateUserInputFromJSONTyped(json, false);
}

export function CreateUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function CreateUserInputToJSON(value?: CreateUserInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'email': value.email,
        'password': value.password,
    };
}

