import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {/* <nav>Navbar in root layout</nav> */}
          <div className="flex flex-col items-center justify-between p-24">
            <Link href="/todos">todos</Link>
            <Link href="/todos/1">todos/1</Link>
            <Link href="/todos/2">todos/2</Link>
          </div>
          {children}{' '}
        </div>
      </body>
    </html>
  )
}
