import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav>Navbar in root layout</nav> */}
        <div>
          <div className="w-full fixed top-0 flex flex-row items-center justify-between p-4">
            <Link href="/todos">todos</Link>
            <Link href="/feature">feature</Link>
            <Link href="/todos/1">todos/1</Link>
            <Link href="/todos/2">todos/2</Link>
          </div>
          {children}{' '}
        </div>
      </body>
    </html>
  )
}
