/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TestRunCase,
} from '../models';
import {
    TestRunCaseFromJSON,
    TestRunCaseToJSON,
} from '../models';

export interface TestRunCasesIdDeleteRequest {
    id: number;
}

export interface TestRunCasesIdGetRequest {
    id: number;
}

export interface TestRunCasesIdPutRequest {
    id: number;
    testRunCase?: TestRunCase;
}

export interface TestRunCasesPostRequest {
    testRunCase?: TestRunCase;
}

export interface TestRunCasesTestrunTestRunIDGetRequest {
    testRunID: number;
}

/**
 * 
 */
export class TestRunCasesApi extends runtime.BaseAPI {

    /**
     */
    async testRunCasesIdDeleteRaw(requestParameters: TestRunCasesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling testRunCasesIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/TestRunCases/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testRunCasesIdDelete(requestParameters: TestRunCasesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testRunCasesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async testRunCasesIdGetRaw(requestParameters: TestRunCasesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling testRunCasesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/TestRunCases/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testRunCasesIdGet(requestParameters: TestRunCasesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testRunCasesIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async testRunCasesIdPutRaw(requestParameters: TestRunCasesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling testRunCasesIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/TestRunCases/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TestRunCaseToJSON(requestParameters.testRunCase),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testRunCasesIdPut(requestParameters: TestRunCasesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testRunCasesIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async testRunCasesPostRaw(requestParameters: TestRunCasesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/TestRunCases`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TestRunCaseToJSON(requestParameters.testRunCase),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testRunCasesPost(requestParameters: TestRunCasesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testRunCasesPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async testRunCasesTestrunTestRunIDGetRaw(requestParameters: TestRunCasesTestrunTestRunIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.testRunID === null || requestParameters.testRunID === undefined) {
            throw new runtime.RequiredError('testRunID','Required parameter requestParameters.testRunID was null or undefined when calling testRunCasesTestrunTestRunIDGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/TestRunCases/testrun/{testRunID}`.replace(`{${"testRunID"}}`, encodeURIComponent(String(requestParameters.testRunID))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testRunCasesTestrunTestRunIDGet(requestParameters: TestRunCasesTestrunTestRunIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.testRunCasesTestrunTestRunIDGetRaw(requestParameters, initOverrides);
    }

}
