/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTestRunInput
 */
export interface CreateTestRunInput {
    /**
     * 
     * @type {string}
     * @memberof CreateTestRunInput
     */
    testRunName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestRunInput
     */
    testRunDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTestRunInput
     */
    userID?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestRunInput
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateTestRunInput
     */
    endTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateTestRunInput
     */
    testRunStatus?: number;
}

/**
 * Check if a given object implements the CreateTestRunInput interface.
 */
export function instanceOfCreateTestRunInput(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTestRunInputFromJSON(json: any): CreateTestRunInput {
    return CreateTestRunInputFromJSONTyped(json, false);
}

export function CreateTestRunInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestRunInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testRunName': !exists(json, 'testRunName') ? undefined : json['testRunName'],
        'testRunDate': !exists(json, 'testRunDate') ? undefined : (new Date(json['testRunDate'])),
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
        'startTime': !exists(json, 'startTime') ? undefined : (new Date(json['startTime'])),
        'endTime': !exists(json, 'endTime') ? undefined : (new Date(json['endTime'])),
        'testRunStatus': !exists(json, 'testRunStatus') ? undefined : json['testRunStatus'],
    };
}

export function CreateTestRunInputToJSON(value?: CreateTestRunInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testRunName': value.testRunName,
        'testRunDate': value.testRunDate === undefined ? undefined : (value.testRunDate.toISOString()),
        'userID': value.userID,
        'startTime': value.startTime === undefined ? undefined : (value.startTime.toISOString()),
        'endTime': value.endTime === undefined ? undefined : (value.endTime.toISOString()),
        'testRunStatus': value.testRunStatus,
    };
}

