/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestCase
 */
export interface TestCase {
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    testCaseID?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    featureID?: number;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    testCaseName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    testCaseOrder?: number;
}

/**
 * Check if a given object implements the TestCase interface.
 */
export function instanceOfTestCase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TestCaseFromJSON(json: any): TestCase {
    return TestCaseFromJSONTyped(json, false);
}

export function TestCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestCase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testCaseID': !exists(json, 'testCaseID') ? undefined : json['testCaseID'],
        'featureID': !exists(json, 'featureID') ? undefined : json['featureID'],
        'testCaseName': !exists(json, 'testCaseName') ? undefined : json['testCaseName'],
        'testCaseOrder': !exists(json, 'testCaseOrder') ? undefined : json['testCaseOrder'],
    };
}

export function TestCaseToJSON(value?: TestCase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testCaseID': value.testCaseID,
        'featureID': value.featureID,
        'testCaseName': value.testCaseName,
        'testCaseOrder': value.testCaseOrder,
    };
}

