/* tslint:disable */
/* eslint-disable */
/**
 * ServerC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserInput
 */
export interface UpdateUserInput {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInput
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserInput
     */
    password: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserInput
     */
    userID?: number;
}

/**
 * Check if a given object implements the UpdateUserInput interface.
 */
export function instanceOfUpdateUserInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userName" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function UpdateUserInputFromJSON(json: any): UpdateUserInput {
    return UpdateUserInputFromJSONTyped(json, false);
}

export function UpdateUserInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'email': json['email'],
        'password': json['password'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function UpdateUserInputToJSON(value?: UpdateUserInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'email': value.email,
        'password': value.password,
        'userID': value.userID,
    };
}

